$cl_primary   = rgba({{colors.primary.default.hex_stripped}}ff)
$cl_secondary = rgba({{colors.secondary.default.hex_stripped}}ff)
$cl_tertiary  = rgba({{colors.tertiary.default.hex_stripped}}ff)
$cl_surface_v = rgba({{colors.surface_variant.default.hex_stripped}}ff)
general {
    col.active_border   = $cl_primary $cl_tertiary 45deg
    col.inactive_border = $cl_surface_v
}
