# disabled for current Hyprland syntax: layerrule = blur, waybar
# disabled for current Hyprland syntax: layerrule = ignorezero, waybar
# disabled for current Hyprland syntax: layerrule = blurpopups, waybar

# disabled for current Hyprland syntax: layerrule = blur, logout_dialog
# disabled for current Hyprland syntax: layerrule = animation popin 95%, logout_dialog

# disabled for current Hyprland syntax: layerrule = blur, rofi
# disabled for current Hyprland syntax: layerrule = ignorezero, rofi
# disabled for current Hyprland syntax: layerrule = animation popin 95%, rofi
# disabled for current Hyprland syntax: layerrule = unset, rofi

# disabled for current Hyprland syntax: layerrule = blur, swaync-control-center
# disabled for current Hyprland syntax: layerrule = ignorezero, swaync-control-center
# disabled for current Hyprland syntax: layerrule = animation popin 95%, swaync-control-center

# disabled for current Hyprland syntax: layerrule = blur, swaync-notification-window
# disabled for current Hyprland syntax: layerrule = ignorezero, swaync-notification-window
# disabled for current Hyprland syntax: layerrule = animation slide, swaync-notification-window

